version: '2'
services:
  app:
    image: node:6
    stdin_open: true
    ports:
     - 3000:3000
    volumes:
     - .:/opt/conv.ai
     - ./docker/yarn:/opt/yarn
    links:
     - mongo
     - elasticsearch
    depends_on:
     - mongo
     - elasticsearch
    environment:
     - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/yarn/bin:./node_modules/.bin
     - TERM=xterm
     - NODE_ENV=development
    working_dir: /opt/conv.ai
    command: ["./docker-entrypoint.sh"]
  mongo:
    image: mongo
    volumes:
      - ./docker/mongodb:/data/db
    expose:
      - 27017
  elasticsearch:
    image: elasticsearch
    volumes:
     - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    image: kibana
    ports:
     - 5601:5601
    depends_on:
     - elasticsearch
