#!/usr/bin/env node

const argv = require('yargs')
  .demand([
    'token'
  ])
  .describe('token', 'The Page Access Token, found in App settings.')
  .describe('verify', 'A verification token for the first-time setup of your webhook.')
  .argv

const co = require('co')
const uuid = require('uuid')
const chalk = require('chalk')
const request = require('request-promise')
const Bot = require('../src/models/bot')

co(function* () {
  // Get page infos
  const { name } = yield request({
    uri: 'https://graph.facebook.com/v2.6/me',
    qs: {
      access_token: argv.token
    },
    json: true
  })

  // Save bot config
  const bot = yield new Bot({
    name,
    messenger: {
      token: argv.token,
      verify: argv.verify || uuid.v4()
    }
  }).save()

  // Create bot start button
  yield request({
    method: 'POST',
    uri: 'https://graph.facebook.com/v2.6/me/thread_settings',
    qs: {
      access_token: argv.token
    },
    json: {
      setting_type: 'call_to_actions',
      thread_state: 'new_thread',
      call_to_actions: [{
        payload: 'start'
      }]
    }
  })

  // Output useful infos
  console.log(chalk.green('Bot created!'))
  console.log(chalk.blue('Webhook URL:'), chalk.bold(`/messenger/${bot.id}`))
  console.log(chalk.blue('Verify token:'), chalk.bold(bot.messenger.verify))
})
.then(() => process.exit())
.catch(err => {
  console.error(chalk.red(err))
  process.exit(1)
})

