#!/usr/bin/env node

const argv = require('yargs')
  .demand([
    'token'
  ])
  .describe('token', 'The Page Access Token, found in App settings.')
  .describe('verify', 'A verification token for the first-time setup of your webhook.')
  .argv

const co = require('co')
const uuid = require('uuid')
const request = require('request-promise')
const Bot = require('../src/models/bot')

co(function* () {
  const { name } = yield request({
    uri: 'https://graph.facebook.com/v2.6/me',
    qs: {
      access_token: argv.token
    },
    json: true
  })

  const bot = yield new Bot({
    name,
    messenger: {
      token: argv.token,
      verify: argv.verify || uuid.v4()
    }
  }).save()

  console.log('Bot created!')
  console.log('Webhook URL:', `/messenger/${bot.id}`)
  console.log('Verify token:', bot.messenger.verify)
})
.then(() => process.exit())
.catch(err => {
  console.error(err)
  process.exit(1)
})

